version: '3'

services:
  blood-sugar-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blood-sugar-app
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
    volumes:
      - ./dist:/app/dist
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
